import Header from "@/components/header/page";
import { DM_Mono } from "next/font/google";
import "./globals.css"

const dmmono = DM_Mono({ weight: "500", subsets: ["latin"] });
export const metadata = {
  title: "GorevKutusu",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="tr">
      <body className={`${dmmono.className}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}